# Site settings
title: JQ Blog
url: "http://jqroom.com"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "http://jqroom.com/" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
timezone: Asia/Shanghai
description: >
  JQ's github page blog.

# Your information
email: jqroom.com@gmail.com
author: JQ
avatar: "//avatars2.githubusercontent.com/u/18415185?v=3&s=460"
profile: 悟已往之不谏，知来者之可追；实迷途其未远，觉今是而昨非。
#twitter_username: twitter_username
github_username:  jqroom

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
